FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/server

WORKDIR /server

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY /server /server/server

CMD ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--reload"]

